server:
  port: 8080

spring:

#  ==== redis ====
  redis:
    database: 0
    host: 124.71.153.92
    port: 6379
    password: (\redis*nmsl/!!)
    #连接超时时间
    timeout: 5000

  #    ==== mongodb ====
  data:
    mongodb:
#      uri: mongodb://124.71.153.92:27017/
      uri: mongodb://email:*%2Femailasddsa#@124.71.153.92:27017/?authSource=admin
    web:
      pageable:
        one-indexed-parameters: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

#   ==== druid ====
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.71.153.92:3306/email?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: nmcb
      password: +nmcb*mysql
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 15
      # 最大连接数
      max-active: 30
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 连接在池中最大生存的时间
      max-evictable-idle-time-millis: 900000
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
      test-while-idle: true
      # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个
      test-on-borrow: true
      # 是否在归还到池中前进行检验
      test-on-return: false
      # 检测连接是否有效
      validation-query: select 1
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

mongo:
  config:
    minConnectionPerHost: 0
    maxConnectionPerHost: 100
    threadsAllowedToBlockForConnectionMultiplier: 5
    serverSelectionTimeout: 30000
    maxWaitTime: 10000
    maxConnectionIdleTime: 1000
    maxConnectionLifeTime: 1000
    connectTimeout: 10000
    socketTimeout: 5000
    socketKeepAlive: true
    sslEnabled: false
    sslInvalidHostNameAllowed: false
    alwaysUseMBeans: false
    heartbeatFrequency: 500
    minHeartbeatFrequency: 20000
    heartbeatSocketTimeout: 20000
    localThreshold: 15
    receiveBufferSize: 0
    sendBufferSize: 0

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认10小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 36000000
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAJB6bTjKzAO0WBcF1u6ImZvmUDnDgABHZzcSon6+Kk7rSessRokzHZUAy2VvwrDxkg+92kBbeD7mv8l/cumb8+V1v52lkVIQPizoTdXNjGRiFJz6rMLwNdU7rrE9eB0BAjHspFw5/EzK1cVPtsfID6tDnqK378L4Ypn1AkICgJMvAgMBAAECgYAPn52WCaAcOnFYNAJ1EwKBcFt2k6SQ4yfPNc2qpQfQNvNsYgJSrdtiFI7qLjbAia8A0sf6M6oCK1PMB2M2ze2G1eaJB3XMU7mXD6bVTy1bTSbwTf5+sGxyOeCd3opzldDKLN0sZQp+LwWF2skPwMXD2mJa5LkSy23Uteh8evJlcQJBANbPXKEqZP5zt8Q2OaLCj6/npOnCigUWlH2OfpOHUVuDYtkcB6R1xPKiYZxJpG6eDTvLehLfvbPkIpG6bdN0t5kCQQCsLpqZ4hNEp3+uFXrvIEpv2JtFFUFyQFqO/drFq8wIvxI0UbQxSilwGzpdmjMRk9a8ynq2VI/1sDO0JtXB7L4HAkEA0sWavSSs/iMrMGKIgRRpCo+/eAMDjGSQhPY5aqZ/BM1RQ3jGYu+PtQfxwPldV5DLqV1JRZW2PPnflaAYvUAsGQJBAIrLgop7SCb2kqDk5dUvBXIFfJyCluAfaiCMF7dyViXSyDzug7+b1a1t9W2QqIwJzXcgDS0/G1DkubkF+Re63C8CQQDUGFN5Ms0eK+cV1mOnq3VFrNMDD5gFgMCRYq7+Jt3bFw1fEtLXqJjD3Pc1Izas6Wk4t9YXkYvVTq4UkAOKhpfn

upload:
  upload-path: J:\file\static\
